export default {
  FETCH_TABLES: 'table/FETCH_TABLES',
  GET_ALL_TABLES: 'table/GET_ALL_TABLES',
  RESERVE_TABLE: 'table/RESERVE_TABLE',
  GET_RESERVED_TABLE: 'table/GET_RESERVED_TABLE',

  ADD_PRODUCT_TO_ORDER: 'order/ADD_PRODUCT_TO_ORDER',
  REMOVE_PRODUCT_FROM_ORDER: 'order/REMOVE_PRODUCT_FROM_ORDER',
  GET_TOTAL: 'order/GET_TOTAL',
  GET_ORDERED_PRODUCTS: 'order/GET_ORDERED_PRODUCTS',
  GET_ORDERED_PRODUCTS_BY_CATEGORY: 'order/GET_ORDERED_PRODUCTS_BY_CATEGORY',
  GET_ORDERED_TIME: 'order/GET_ORDERED_TIME',
  SEND_TO_KITCHEN: 'order/SEND_TO_KITCHEN'
};